"""Typeset frozen E0 estimates without rerunning statistics or changing coding."""
from pathlib import Path
import argparse
import json
from sok_systematization import tex, digest

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs/sok/e0-current/analysis'
SOURCE = OUT / 'results.json'
GROUPS = [
    ('Timing, workload, and comparison', ['endpoint','denominator','tail','deadline','load','queue','stability','baseline']),
    ('Control-loop claim and deployment', ['loop_claim','loop_match','deployment','roundtrip']),
    ('Validation responsibilities', ['format','semantic','final_state','gate_separation']),
    ('Artifact pointers', ['code','data']),
]
STRATA = [('unchanged_initial','Initial comparable answers',231),
          ('aligned_recheck','Independent aligned recheck',174),
          ('all_scopes','Combined, before adjudication',405),
          ('new_steps','Step-definition scopes',374),
          ('linked_scopes','Linked scopes',31)]


def coverage(s, stacked=True):
    assert s['n'] > 0 and abs(s['proportion']-s['positive']/s['n']) < 1e-12
    lo, hi = s['ci95']
    assert 0 <= lo <= hi <= 1
    if not stacked:
        return f"{s['positive']}/{s['n']} ({100*s['proportion']:.1f}"+r'\%); '+f'[{100*lo:.1f}, {100*hi:.1f}]'
    return (r'\shortstack[r]{' + f"{s['positive']}/{s['n']} ({100*s['proportion']:.1f}"
            + r'\%)\\{' + f'[{100*lo:.1f}, {100*hi:.1f}]' + '}}')


def coefficient(v):
    return 'N/A' if v is None else f'{v:.3f}'


def begin(caption, label, columns, heading, ncols, continued=None):
    long = continued is not None
    lines = ['% Generated by scripts/sok_e0_tables.py from frozen results.json; no reanalysis.',
             r'\begingroup\footnotesize',r'\setlength{\tabcolsep}{4pt}',
             r'\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}',
             r'\renewcommand{\arraystretch}{1.10}']
    if long:
        lines += [r'\setlength{\LTcapwidth}{\textwidth}',r'\begin{longtable}{'+columns+'}',
                  r'\caption{'+caption+r'}\label{'+label+r'}\\',r'\toprule',heading,
                  r'\midrule\endfirsthead',r'\caption[]{'+continued+r'}\\',r'\toprule',heading,
                  r'\midrule\endhead',r'\bottomrule\endfoot']
    else:
        lines += [r'\begin{table*}[t]',r'\centering',r'\caption{'+caption+'}',r'\label{'+label+'}',
                  r'\begin{tabular}{'+columns+'}',r'\toprule',heading,r'\midrule']
    return lines


def end(lines, name, long=False):
    lines += ([r'\end{longtable}'] if long else [r'\bottomrule',r'\end{tabular}',r'\end{table*}'])
    lines += [r'\endgroup','']
    (OUT/name).write_text('\n'.join(lines))


def band(title, n):
    return r'\rowcolor{ebAmber!35}\multicolumn{'+str(n)+r'}{@{}l}{\textbf{'+tex(title)+r'}} \\*'


def reader_tables(data):
    """Compact scientific summaries of the unchanged categorical results."""
    names = dict(model='Model return', dispatch='Dispatch', network='Network effect',
                 service='Service result', other='Other', not_reported='Not reported',
                 all='All attempts', success='Successful', mixed='Mixed', yes='Reported',
                 rt='RT/fast', near_rt='Near-RT', non_rt='Non-RT', not_stated='Not stated',
                 matched='Matched', mismatch='Mismatch', insufficient='Insufficient',
                 hosted='Hosted API', gpu='Local GPU', edge='Edge device', cpu='Local CPU',
                 included='Included', excluded='Excluded', reported='Reported',
                 explicit_no='Explicitly unchecked', three='All three', partial='Partial',
                 no='Combined', public_link='Public link', on_request='On request/private',
                 unclear='Unclear', na='N/A')
    metrics = {row['field']: row for row in data['metrics']}
    preamble = ['% Generated by scripts/sok_e0_tables.py --reader-appendix; frozen estimates only.',
                r'\begingroup\footnotesize', r'\setlength{\tabcolsep}{4pt}',
                r'\setlength{\aboverulesep}{0pt}\setlength{\belowrulesep}{0pt}',
                r'\renewcommand{\arraystretch}{1.10}', r'\setlength{\LTcapwidth}{\textwidth}']
    heading = r'\rowcolor{ebBlue} Field & Response category: number of scopes \\'
    lines = preamble + [
        r'\newlength{\sokcategorywidth}',
        r'\setlength{\sokcategorywidth}{\dimexpr\textwidth-1pt-4\tabcolsep\relax}',
        r'\begin{longtable}{>{\raggedright\arraybackslash}p{.27\sokcategorywidth}'
        r'>{\raggedright\arraybackslash}p{.73\sokcategorywidth}}',
        r'\caption{Adjudicated category counts across 405 scopes. Each single-choice row sums to 405; '
        r'timing endpoint and execution location allow multiple selections. N/A denotes inapplicability; '
        r'unlisted response categories have zero count. Table~\ref{tab:e0-audit} '
        r'reports positive coverage and its family-clustered intervals.}\label{tab:e0-categories}\\',
        r'\toprule', heading, r'\midrule\endfirsthead',
        r'\caption[]{Adjudicated category counts (continued).}\\',
        r'\toprule', heading, r'\midrule\endhead', r'\bottomrule\endfoot']
    for group, fields in GROUPS:
        lines.append(band(group, 2).replace('ebAmber!35', 'ebAmber!45')
                     .replace(r'\textbf{', r'\textbf{\itshape ').replace('{@{}l}', '{l}'))
        for field in fields:
            rows = [r for r in data['category_distributions'] if r['field'] == field]
            assert all(r['scope']['n'] == 405 for r in rows)
            values = {r['category']: r['scope']['positive'] for r in rows}
            if field not in ['endpoint', 'deployment']:
                assert sum(values.values()) == 405, field
            labels = dict(names)
            if field in ['code', 'data']:
                labels['explicit_no'] = 'Not public'
            categories = '; '.join(f'{tex(labels[k])}:~{v}' for k, v in values.items() if v)
            lines.append(' & '.join([tex(metrics[field]['label']), categories]) + r' \\')
            lines.append(r'\addlinespace[3pt]')
    lines += [r'\end{longtable}', r'\endgroup', '']
    outputs = {'e0-categories-table.tex': '\n'.join(lines)}

    heading = (r'\rowcolor{ebBlue} Option & \shortstack{Researcher 1\\selected} & '
               r'\shortstack{Researcher 2\\selected} & A (\%) & $\kappa$ & AC1 \\')
    lines = preamble + [
        r'\newlength{\sokoptionwidth}',
        r'\setlength{\sokoptionwidth}{\dimexpr\textwidth-1pt-12\tabcolsep\relax}',
        r'\begin{longtable}{>{\raggedright\arraybackslash}p{.30\sokoptionwidth}'
        r'>{\raggedleft\arraybackslash}p{.18\sokoptionwidth}'
        r'>{\raggedleft\arraybackslash}p{.18\sokoptionwidth}'
        r'>{\raggedleft\arraybackslash}p{.12\sokoptionwidth}'
        r'>{\raggedleft\arraybackslash}p{.11\sokoptionwidth}'
        r'>{\raggedleft\arraybackslash}p{.11\sokoptionwidth}}',
        r'\caption{Pre-adjudication option agreement for the two multi-select fields over all 405 paired scopes '
        r'(231 initial pairs and 174 independent rechecks after scope alignment). Counts give the number '
        r'of selections by each researcher. A counts both joint selections and joint non-selections. '
        r'N/A denotes undefined $\kappa$ for a constant category.}\label{tab:e0-agreement-options}\\',
        r'\toprule', heading, r'\midrule\endfirsthead',
        r'\caption[]{Multi-select option agreement (continued).}\\',
        r'\toprule', heading, r'\midrule\endhead', r'\bottomrule\endfoot']
    for field, title in [('endpoint', 'Timing endpoint'), ('deployment', 'Execution location')]:
        lines.append(band(title, 6).replace('ebAmber!35', 'ebAmber!45')
                     .replace(r'\textbf{', r'\textbf{\itshape ').replace('{@{}l}', '{l}'))
        rows = [r for r in data['multi_option_agreement'] if r['field'] == field and r['stratum'] == 'all_scopes']
        assert len(rows) == (8 if field == 'endpoint' else 7)
        for row in rows:
            assert row['n_pairs'] == 405
            assert sum(row['DL_categories'].values()) == sum(row['CL_categories'].values()) == 405
            cells = [tex(names[row['option']]), str(row['DL_categories'].get('1', 0)),
                     str(row['CL_categories'].get('1', 0)), f"{100*row['agreement']:.1f}",
                     coefficient(row['kappa']), coefficient(row['ac1'])]
            lines.append(' & '.join(cells) + r' \\')
    lines += [r'\end{longtable}', r'\endgroup', '']
    outputs['e0-agreement-options.tex'] = '\n'.join(lines)
    for name, text in outputs.items():
        lines = text.splitlines()
        assert lines.count(r'\begingroup\footnotesize') == 1
        lines[lines.index(r'\begingroup\footnotesize')] = r'\begin{table}[!htbp]' + '\n' + r'\centering\footnotesize'
        assert lines.count(r'\setlength{\LTcapwidth}{\textwidth}') == 1
        lines.pop(lines.index(r'\setlength{\LTcapwidth}{\textwidth}'))
        start = next(i for i, line in enumerate(lines) if line.startswith(r'\begin{longtable}'))
        table = lines.pop(start).replace(r'\begin{longtable}', r'\begin{tabular}')
        assert lines[start].startswith(r'\caption') and lines[start].endswith('\\\\')
        lines[start] = lines[start][:-2]
        lines.insert(start + 1, table)
        first, last = lines.index(r'\midrule\endfirsthead'), lines.index(r'\bottomrule\endfoot')
        lines[first:last + 1] = [r'\midrule']
        assert lines[-2:] == [r'\end{longtable}', r'\endgroup']
        lines[-2:] = [r'\bottomrule', r'\end{tabular}', r'\end{table}']
        text = '\n'.join(lines) + '\n'
        if name == 'e0-categories-table.tex':
            old = 'Adjudicated category counts across 405 scopes. Each single-choice row sums to 405; timing endpoint and execution location allow multiple selections. N/A denotes inapplicability; unlisted response categories have zero count.'
            new = 'Adjudicated category counts across the 405 scopes coded by the two researchers. Each single-choice row sums to 405. Timing endpoint and execution location allow multiple selections. N/A denotes inapplicability, and unlisted response categories have zero count.'
            assert text.count(old) == 1
            text = text.replace(old, new)
        outputs[name] = text
    return outputs


def main():
    data = json.loads(SOURCE.read_text())
    assert data['counts'] == dict(paper_families=132,reports=138,scope_records=405,step_definitions=374,
                                 linked_scopes=31,unclear_cells=320,pre_adjudication_disagreements=1867)
    assert data['metadata']['bootstrap_seed'] == 42 and data['metadata']['bootstrap_replicates'] == 10000
    metrics = {m['field']:m for m in data['metrics']}
    ordered = [f for _, fs in GROUPS for f in fs]
    assert len(metrics) == len(ordered) == 18 and set(metrics) == set(ordered)
    agreements = {(a['stratum'],a['field']):a for a in data['agreement']}
    labels = {f:m['label'] for f,m in metrics.items()}
    sources = []

    caption = (r'Literature reporting coverage. Cells give count/denominator, percentage, '
               r'and a 95\% paper-family bootstrap interval (10,000 draws). A family is positive if any retained scope '
               r'has the target code. The 374 step-definition scopes exclude 31 linked scopes. Unclear counts families '
               r'with any unclear scope; all-NA counts families whose scopes are all not applicable. Unclear can overlap '
               r'positive coverage. All entries remain in their stated denominators. These are reporting categories, '
               r'not evidence that every step or deployed system satisfies the property.')
    heading = (r'\rowcolor{ebBlue} Field & Families (132) & All scopes (405) & Step definitions (374) & '
               r'\shortstack{Unclear\\families} & \shortstack{All-NA\\families} \\')
    lines = begin(caption,'tab:e0-audit','@{}lrrrrr@{}',heading,6)
    for group, fields in GROUPS:
        lines.append(band(group,6))
        for field in fields:
            m=metrics[field]
            assert [m['paper_family']['All']['n'],m['scope']['n'],m['new_step_scope_only']['n']] == [132,405,374]
            lines.append(' & '.join([tex(m['label']),coverage(m['paper_family']['All']),coverage(m['scope']),
                coverage(m['new_step_scope_only']),str(m['families_with_unclear_any_scope']),
                str(m['families_all_scopes_na'])])+r' \\')
            lines.append(r'\addlinespace[1.5pt]')
            sources.append(dict(table='tab:e0-audit',field=field,source_pointer='/metrics/'+str(data['metrics'].index(m))))
    end(lines,'e0-audit-table.tex')

    # Pre-adjudication agreement is kept separate from final reporting coverage.
    for selected, name, label, caption in [
        (STRATA[:3],'e0-agreement-table.tex','tab:e0-agreement',
         r'Independent coding agreement before adjudication. The combined view joins 231 initially comparable '
         r'scope pairs with 174 independent scope-pair rechecks after boundary alignment; it is not an unchanged first-pass estimate. '
         r'A is exact agreement (\%), followed by unweighted Cohen $\kappa$ and Gwet AC1 using codebook categories. '
         r'For the two multi-select fields, A is exact-set agreement and aggregate coefficients are N/A; option-wise '
         r'binary coefficients appear in Table~\ref{tab:e0-agreement-options}. Adjudication and the post-unblinding '
         r'C1 clarification do not supply independent-agreement evidence.'),
        (STRATA[3:],'e0-agreement-sensitivity.tex','tab:e0-agreement-sensitivity',
         r'Pre-adjudication agreement by scope type. Step-definition and linked scopes partition the 405 comparable '
         r'scope records. A is exact agreement (\%); $\kappa$ and AC1 use the same definitions as '
         r'Table~\ref{tab:e0-agreement}. N/A denotes a multi-select field summarized by exact-set agreement; '
         r'option-wise coefficients are reported separately.')]:
        ncols=1+3*len(selected)
        short_titles={'unchanged_initial':'Initial comparable','aligned_recheck':'Aligned recheck',
                      'all_scopes':'Combined','new_steps':'Step-definition','linked_scopes':'Linked'}
        heading=r'\rowcolor{ebBlue} Field & '+' & '.join(
            r'\multicolumn{3}{c}{\shortstack{'+short_titles[stratum]+r'\\'+f'$n={n}$'+'}}'
            for stratum,_,n in selected)+r' \\'
        heading+='\n'+r'\rowcolor{ebBlue} & '+' & '.join([r'A (\%) & $\kappa$ & AC1']*len(selected))+r' \\'
        lines=begin(caption,label,'@{}l'+'r'*(ncols-1)+'@{}',heading,ncols)
        for group,fields in GROUPS:
            lines.append(band(group,ncols))
            for field in fields:
                values=[tex(labels[field])]
                for stratum,_,n in selected:
                    a=agreements[stratum,field];assert a['n_pairs']==n
                    values += [f"{100*a['agreement']:.1f}",coefficient(a['kappa']),coefficient(a['ac1'])]
                    sources.append(dict(table=label,field=field,stratum=stratum,
                                        source_pointer='/agreement/'+str(data['agreement'].index(a))))
                lines.append(' & '.join(values)+r' \\')
        end(lines,name)

    heading=r'\rowcolor{ebBlue} Field & Option & Paired scopes & A (\%) & $\kappa$ & AC1 \\'
    lines=begin(r'Option-wise binary agreement for the two multi-select fields before adjudication. '
                r'A counts both joint selections and joint non-selections; a high value can therefore reflect '
                r'a prevalent negative category. The initial and aligned strata partition the combined view; '
                r'the step-definition and linked strata provide a different partition. N/A denotes undefined '
                r'$\kappa$ when both coders assign the same constant category.',
                'tab:e0-agreement-options','@{}llrrrr@{}',heading,6,
                'Option-wise binary agreement (continued). A: exact agreement (\%).')
    for stratum,title,n in STRATA:
        lines.append(band(f'{title} ({n} paired scopes)',6))
        rows=[a for a in data['multi_option_agreement'] if a['stratum']==stratum]
        assert len(rows)==15
        for a in rows:
            assert a['n_pairs']==n
            lines.append(' & '.join([tex(a['field']),r'\texttt{'+tex(a['option'])+'}',str(n),
                f"{100*a['agreement']:.1f}",coefficient(a['kappa']),coefficient(a['ac1'])])+r' \\')
            sources.append(dict(table='tab:e0-agreement-options',field=a['field'],option=a['option'],stratum=stratum,
                                source_pointer='/multi_option_agreement/'+str(data['multi_option_agreement'].index(a))))
    end(lines,'e0-agreement-options.tex',long=True)

    heading=r'\rowcolor{ebBlue} Field & Codebook category & All scopes (405) & Families with any scope (132) \\'
    lines=begin(r'Complete adjudicated code distributions. Cells give count/denominator, percentage and a 95\% '
                r'paper-family bootstrap interval. Single-choice scope categories sum to 405; multi-select options '
                r'can overlap. Family categories can overlap because a family contains several scopes. A degenerate '
                r'empirical interval at zero or full coverage does not establish a known population prevalence.',
                'tab:e0-categories','@{}llrr@{}',heading,4,
                'Complete adjudicated code distributions (continued). Counts, percentages, and 95\% intervals.')
    for field in ordered:
        lines.append(band(labels[field],4))
        for a in data['category_distributions']:
            if a['field'] != field:continue
            lines.append(' & '.join([tex(field),r'\texttt{'+tex(a['category'])+'}',coverage(a['scope'],stacked=False),
                                     coverage(a['paper_family_any'],stacked=False)])+r' \\')
            sources.append(dict(table='tab:e0-categories',field=field,category=a['category'],
                                source_pointer='/category_distributions/'+str(data['category_distributions'].index(a))))
    end(lines,'e0-categories-table.tex',long=True)

    outputs=['e0-audit-table.tex','e0-agreement-table.tex','e0-agreement-sensitivity.tex',
             'e0-agreement-options.tex','e0-categories-table.tex']
    manifest=dict(status='FROZEN_ESTIMATES_TYPESET_PENDING_LAYOUT_CHECK',source=str(SOURCE.relative_to(ROOT)),
                  source_sha256=digest(SOURCE),generator=str(Path(__file__).relative_to(ROOT)),
                  generator_sha256=digest(Path(__file__)),
                  outputs={name:digest(OUT/name) for name in outputs},row_sources=sources,
                  scientific_boundary='Formatting only. No new coding, adjudication, bootstrap, or reliability claim.',
                  missing_coefficients='N/A means no aggregate kappa/AC1 for exact-set multi-select fields, '
                                       'or undefined binary kappa for matching constant categories. Neither is a zero value.')
    (OUT/'e0-tables-source.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(json.dumps(dict(status=manifest['status'],coverage_fields=18,agreement_field_strata=90,
                         binary_option_strata=75,category_rows=92,source_sha256=manifest['source_sha256'])))


if __name__=='__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reader-appendix', action='store_true',
                        help='Render compact category and multi-select tables in the current paper')
    args = parser.parse_args()
    if args.reader_appendix:
        outputs = reader_tables(json.loads(SOURCE.read_text()))
        for name, content in outputs.items():
            (ROOT/'paper-sok-csur/tables'/name).write_text(content)
        print('Rendered 18 field distributions and 15 multi-select options from frozen results.')
    else:
        main()
